// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCsZyDbPDglTmkwUl2FdKuwX7fjUwwpzM',
    appId: '1:719309857414:web:171386618aeaee95b22707',
    messagingSenderId: '719309857414',
    projectId: 'chat-app-924fb',
    authDomain: 'chat-app-924fb.firebaseapp.com',
    storageBucket: 'chat-app-924fb.appspot.com',
    measurementId: 'G-RJD4TYMNZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyYyT6YQ0PraNwZsDbxfFT1QwICljkxNo',
    appId: '1:719309857414:android:ace2e470752fac51b22707',
    messagingSenderId: '719309857414',
    projectId: 'chat-app-924fb',
    storageBucket: 'chat-app-924fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcSlFD05dM4GrxK2nuHBqEuNl4ib1BYI0',
    appId: '1:719309857414:ios:abc43c6630ded96eb22707',
    messagingSenderId: '719309857414',
    projectId: 'chat-app-924fb',
    storageBucket: 'chat-app-924fb.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcSlFD05dM4GrxK2nuHBqEuNl4ib1BYI0',
    appId: '1:719309857414:ios:abc43c6630ded96eb22707',
    messagingSenderId: '719309857414',
    projectId: 'chat-app-924fb',
    storageBucket: 'chat-app-924fb.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCsZyDbPDglTmkwUl2FdKuwX7fjUwwpzM',
    appId: '1:719309857414:web:4b2c3e1cc102203fb22707',
    messagingSenderId: '719309857414',
    projectId: 'chat-app-924fb',
    authDomain: 'chat-app-924fb.firebaseapp.com',
    storageBucket: 'chat-app-924fb.appspot.com',
    measurementId: 'G-BLDD004FVP',
  );
}
